# Configuration and Infrastructure Security Patterns
# Combines Docker, Nginx, and PostgreSQL RLS patterns for configuration security analysis

patterns:
  # Docker Security Patterns
  - name: "docker-root-user"
    description: "Container running as root user - security risk"
    regex: "^(?!.*USER\\s+(?!root)\\w+).*FROM.*"
    languages: ["dockerfile"]
    severity: "high"
    
  - name: "docker-unpinned-base-image"
    description: "Unpinned base image tag - using :latest or no tag specified"
    regex: "^FROM\\s+[^:]+(:latest)?\\s*$|^FROM\\s+[^:]+\\s*$"
    languages: ["dockerfile"]
    severity: "medium"
    
  - name: "docker-hardcoded-secrets"
    description: "Potential secrets exposed in ARG or ENV instructions"
    regex: "(ARG|ENV)\\s+.*(SECRET|TOKEN|PASSWORD|KEY|API_KEY|PRIVATE|CREDENTIAL|AUTH)\\s*="
    languages: ["dockerfile"]
    severity: "critical"

  # Nginx Security Patterns
  - name: "nginx-missing-security-headers"
    description: "Missing critical security headers (CSP, HSTS)"
    regex: "^(?!.*add_header\\s+(Content-Security-Policy|Strict-Transport-Security)).*server\\s*\\{"
    languages: ["nginx", "conf"]
    severity: "high"
    
  - name: "nginx-weak-ssl-protocols"
    description: "Weak or outdated SSL/TLS protocols enabled"
    regex: "ssl_protocols\\s+.*(SSLv2|SSLv3|TLSv1(?!\\.2|\\.3)|TLSv1\\.0|TLSv1\\.1)"
    languages: ["nginx", "conf"]
    severity: "critical"
    
  - name: "nginx-server-tokens-enabled"
    description: "Server version disclosure enabled - information leak"
    regex: "server_tokens\\s+on\\s*;|^(?!.*server_tokens\\s+off).*http\\s*\\{"
    languages: ["nginx", "conf"]
    severity: "medium"

  # PostgreSQL RLS (Row-Level Security) Patterns
  - name: "postgres-policy-missing-using"
    description: "CREATE POLICY without USING clause - potential data leak"
    regex: "CREATE\\s+POLICY\\s+\\w+\\s+ON\\s+\\w+(?!.*\\bUSING\\b)"
    languages: ["sql", "postgresql"]
    severity: "critical"
    
  - name: "postgres-rls-no-policies"
    description: "Table has RLS enabled but no policies defined"
    regex: "ALTER\\s+TABLE\\s+(\\w+)\\s+ENABLE\\s+ROW\\s+LEVEL\\s+SECURITY(?!.*CREATE\\s+POLICY.*\\1)"
    languages: ["sql", "postgresql"]
    severity: "critical"